apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  password: MTIzNDU2Nzg5Cg==

---
apiVersion: v1
kind: Pod
metadata:
  name: secret-dotfiles-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: mysecret
  containers:
    - name: dotfile-test-container
      image: busybox
#      command:
#        - ls
#        - "-l"
#        - "/etc/secret-volume"
      command: ["echo"]
      args: ["$(password)"]
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"
      env: 
      - name: password
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: password