apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  initContainers:
    - name: myapp1
      image: busybox
#    command: ["sleep"]
#    args: ["100"]
      command: ["/bin/sh","-c"]
      args: ["echo initcontainer; sleep 10"]
  containers:
    - name: myapp2
      image: bash
#    command: ["sleep"]
#    args: ["100"]
      command: ["/bin/sh","-c"]
      args: ["echo First; sleep 100"]