name: "First Program"
on: push
jobs: 
  checkout:
    name: checkout_repository
    runs-on: ubuntu-latest
    steps:
      - name: checkout_github
        uses: actions/checkout@v4.1.1
        with:
          ref: main
      - name: display message
        run: echo "Completed the checkout"

    


    
