name: "CI Pipeline for app service"
on: 
  workflow_dispatch:
jobs: 
  checkout:
    name: checkout_repository
    runs-on: ubuntu-latest
    steps:
      - name: display
        run: echo "Github Action"
