name: "First Program"
on: 
  workflow_dispatch:
jobs:
  display:
    name: display hello work
    runs-on: ubuntu-latest
    steps:
      - name: first job
        run:  echo "Hello from github actions"
