name: "CI Pipeline for app service"
on : workflow_dispatch
jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: display message
        run: echo "starting of CI"

      - name: run multiple commands
        run: | 
              echo "First pipeline is without variable"
              echo "Second pipeline is with variable"
              whoami
              pwd
  
  Buildjob:
    runs-on: ubuntu-latest
    steps:
      - name: buildtheproject
        run: echo "build stage"

  scanningjob:
    runs-on: ubuntu-latest
    steps:  
      - name: scanningjob
        run: echo "Scanning stage"

  nexusrepo:
    runs-on: ubuntu-latest
    steps:
      - name: "Artifacts upload stage"
        run: echo "Artifacts upload on nexus repository"
  



  
