name: "First Program"
on: push
jobs: 
  my_first_job:
    name: display fist name
    runs-on: ubuntu-latest
    steps:
      - name: first name
        run: echo "My first name is Siddhesh"
      - name: Last name
        run: echo "My last name is Dike"
    needs: sec_job
  sec_job:
    name: experience
    runs-on: ubuntu-latest
    steps:
      - name: experience
        run : echo "devops"
    
